namespace Domain.Models
{
    public enum HashType
    {
        MD4 = 900,                                                          //MD4
        MD5 = 0,                                                            //MD5
        SHA1 = 100,                                                         //SHA1
        SHA2_224 = 1300,                                                    //SHA2-224
        SHA2_256 = 1400,                                                    //SHA2-224
        SHA2_384 = 10800,                                                   //SHA2-384
        SHA2_512 = 1700,                                                    //SHA2-512
        SHA3_224 = 17300,                                                   //SHA3-224
        SHA3_256 = 17400,                                                   //SHA3-256
        SHA3_384 = 17500,                                                   //SHA3-384
        SHA3_512 = 17600,                                                   //SHA3-512
        RIPEMD_160 = 6000,                                                  //RIPEMD-160
        BLAKE2b_512 = 600,                                                  //BLAKE2b-512
        GOST_R_34_11_2012_Streebog_256_bit_big_endian = 11700,              //GOST R 34.11-2012 (Streebog) 256-bit, big-endian
        GOST_R_34_11_2012_Streebog_512_bit_big_endian = 11800,              //GOST R 34.11-2012 (Streebog) 512-bit, big-endian
        GOST_R_34_11_94 = 6900,                                             //GOST R 34.11-94
        GPG_AES_128_AES_256_SHA_1_pass = 17010,                             //GPG (AES-128/AES-256 (SHA-1($pass)))
        Half_MD5 = 5100,                                                    //Half MD5
        Keccak_224 = 17700,                                                 //Keccak-224
        Keccak_256 = 17800,                                                 //Keccak-256
        Keccak_384 = 17900,                                                 //Keccak-384
        Keccak_512 = 18000,                                                 //Keccak-512
        Whirlpool = 6100,                                                   //Whirlpool
        SipHash = 10100,                                                    //SipHash
        md5_utf16le_pass = 70,                                              //md5(utf16le($pass))
        sha1_utf16le_pass = 170,                                            //sha1(utf16le($pass))
        sha256_utf16le_pass = 1470,                                         //sha256(utf16le($pass))
        sha384_utf16le_pass = 10870,                                        //sha256(utf16le($pass))
        sha512_utf16le_pass = 1770,                                         //sha512(utf16le($pass))
        BLAKE2b_512pass_salt = 610,                                         //BLAKE2b-512($pass.$salt)
        BLAKE2b_512salt_pass = 620,                                         //BLAKE2b-512($salt.$pass)
        md5_pass_salt = 10,                                                 //md5($pass.$salt)
        md5_salt_pass = 20,                                                 //md5($salt.$pass)
        md5_salt_pass_salt = 3800,                                          //md5($salt.$pass.$salt)
        md5_salt_md5_pass = 3710,                                           //md5($salt.md5($pass))
        md5_salt_md5_pass_salt = 4110,                                      //md5($salt.md5($pass.$salt))
        md5_salt_md5_salt_pass = 4010,                                      //md5($salt.md5($pass.$salt))
        md5_salt_sha1_salt_pass = 21300,                                    //md5($salt.sha1($salt.$pass))
        md5_salt_utf16le_pass = 40,                                         //md5($salt.utf16le($pass))
        md5_md5_pass = 2600,                                                //md5(md5($pass))
        md5_md5_pass_md5_salt = 3910,                                       //md5(md5($pass).md5($salt))
        md5_md5_md5_pass = 3500,                                            //md5(md5(md5($pass)))
        md5_sha1_pass = 4400,                                               //md5(sha1($pass))
        md5_sha1_pass_salt = 4410,                                          //md5(sha1($pass).$salt)
        md5_sha1_pass_md5_pass_sha1_pass = 20900,                           //md5(sha1($pass).md5($pass).sha1($pass))
        md5_sha1_salt_md5_pass = 21200,                                     //md5(sha1($salt).md5($pass))
        md5_strtoupper_md5_pass = 4300,                                     //md5(strtoupper(md5($pass)))
        md5_utf16le_pass_salt = 30,                                         //md5(utf16le($pass).$salt)
        sha1_pass_salt = 110,                                               //sha1($pass.$salt)                          
        sha1_salt_pass = 120,                                               //sha1($salt.$pass)                          
        sha1_salt_pass_salt = 4900,                                         //sha1($salt.$pass.$salt)                    
        sha1_salt_sha1_pass = 4520,                                         //sha1($salt.sha1($pass))                    
        sha1_salt_sha1_pass_salt = 24300,                                   //sha1($salt.sha1($pass.$salt))              
        sha1_salt_utf16le_pass = 140,                                       //sha1($salt.utf16le($pass))                 
        sha1_salt1_pass_salt2 = 19300,                                      //sha1($salt1.$pass.$salt2)                  
        sha1_CX = 14400,                                                    //sha1(CX)                                   
        sha1_md5_pass = 4700,                                               //sha1(md5($pass))                           
        sha1_md5_pass_salt = 4710,                                          //sha1(md5($pass).$salt)                     
        sha1_md5_pass_salt_2 = 21100,                                       //sha1(md5($pass.$salt))                     
        sha1_md5_md5_pass = 18500,                                          //sha1(md5(md5($pass)))                      
        sha1_sha1_pass = 4500,                                              //sha1(sha1($pass))                          
        sha1_sha1_pass_salt = 4510,                                         //sha1(sha1($pass).$salt)                    
        sha1_sha1_salt_pass_salt = 5000,                                    //sha1(sha1($salt.$pass.$salt))              
        sha1_utf16le_pass_salt = 130,                                       //sha1(utf16le($pass).$salt)                 
        sha256_pass_salt = 1410,                                            //sha256($pass.$salt)                        
        sha256_salt_pass = 1420,                                            //sha256($salt.$pass)                        
        sha256_salt_pass_salt = 22300,                                      //sha256($salt.$pass.$salt)                  
        sha256_salt_sha256_pass = 20720,                                    //sha256($salt.sha256($pass))                
        sha256_salt_sha256_bin_pass = 21420,                                //sha256($salt.sha256_bin($pass))            
        sha256_salt_utf16le_pass = 1440,                                    //sha256($salt.utf16le($pass))               
        sha256_md5_pass = 20800,                                            //sha256(md5($pass))                         
        sha256_sha256_pass_salt = 20710,                                    //sha256(sha256($pass).$salt)                
        sha256_sha256_bin_pass = 21400,                                     //sha256(sha256_bin($pass))                  
        sha256_utf16le_pass_salt = 1430,                                    //sha256(utf16le($pass).$salt)               
        sha384_pass_salt = 10810,                                           //sha384($pass.$salt)                        
        sha384_salt_pass = 10820,                                           //sha384($salt.$pass)                        
        sha384_salt_utf16le_pass = 10840,                                   //sha384($salt.utf16le($pass))               
        sha384_utf16le_pass_salt = 10830,                                   //sha384(utf16le($pass).$salt)               
        sha512_pass_salt = 1710,                                            //sha512($pass.$salt)                        
        sha512_salt_pass = 1720,                                            //sha512($salt.$pass)                        
        sha512_salt_utf16le_pass = 1740,                                    //sha512($salt.utf16le($pass))               
        sha512_utf16le_pass_salt = 1730,                                    //sha512(utf16le($pass).$salt)               
        HMAC_MD5_key_pass = 50,                                             //HMAC-MD5 (key = $pass)                     
        HMAC_MD5_key_salt = 60,                                             //HMAC-MD5 (key = $salt)                     
        HMAC_SHA1_key_pass = 150,                                           //HMAC-SHA1 (key = $pass)                    
        HMAC_SHA1_key_salt = 160,                                           //HMAC-SHA1 (key = $salt)                    
        HMAC_SHA256_key_pass = 1450,                                        //HMAC-SHA256 (key = $pass)                  
        HMAC_SHA256_key_salt = 1460,                                        //HMAC-SHA256 (key = $salt)                  
        HMAC_SHA512_key_pass = 1750,                                        //HMAC-SHA512 (key = $pass)                  
        HMAC_SHA512_key_salt = 1760,                                        //HMAC-SHA512 (key = $salt)                  
        HMAC_Streebog_256_key_pass_big_endian = 11750,                      //HMAC-Streebog-256 (key = $pass), big-endian
        HMAC_Streebog_256_key_salt_big_endian = 11760,                      //HMAC-Streebog-256 (key = $salt), big-endian
        HMAC_Streebog_512_key_pass_big_endian = 11850,                      //HMAC-Streebog-512 (key = $pass), big-endian
        HMAC_Streebog_512_key_salt_big_endian = 11860,                      //HMAC-Streebog-512 (key = $salt), big-endian
        Amazon_AWS4_HMAC_SHA256 = 28700,                                    //Amazon AWS4-HMAC-SHA256                    
        CRC32 = 11500,                                                      //CRC32                                      
        CRC32C = 27900,                                                     //CRC32C                                     
        CRC64Jones = 28000,                                                 //CRC64Jones                                 
        Java_Object_hashCode = 18700,                                       //Java Object hashCode()                     
        MurmurHash = 25700,                                                 //MurmurHash                                 
        MurmurHash3 = 27800,                                                //MurmurHash3
        _3DES_PT_salt_key_pass = 14100,                                     //3DES (PT = $salt, key = $pass)                            
        DES_PT_salt_key_pass = 14000,                                       //DES (PT = $salt, key = $pass)                             
        AES_128_ECB_NOKDF_PT_salt_key_pass = 26401,                         //AES-128-ECB NOKDF (PT = $salt, key = $pass)               
        AES_192_ECB_NOKDF_PT_salt_key_pass = 26402,                         //AES-192-ECB NOKDF (PT = $salt, key = $pass)               
        AES_256_ECB_NOKDF_PT_salt_key_pass = 26403,                         //AES-256-ECB NOKDF (PT = $salt, key = $pass)               
        ChaCha20 = 15400,                                                   //ChaCha20                                                  
        Linux_Kernel_Crypto_API_2_4 = 14500,                                //Linux Kernel Crypto API (2.4)                             
        Skip32_PT_salt_key_pass = 14900,                                    //Skip32 (PT = $salt, key = $pass)                          
        PBKDF2_HMAC_MD5 = 11900,                                            //PBKDF2-HMAC-MD5                                           
        PBKDF2_HMAC_SHA1 = 12000,                                           //PBKDF2-HMAC-SHA1                                          
        PBKDF2_HMAC_SHA256 = 10900,                                         //PBKDF2-HMAC-SHA256                                        
        PBKDF2_HMAC_SHA512 = 12100,                                         //PBKDF2-HMAC-SHA512                                        
        scrypt = 8900,                                                      //scrypt                                                    
        phpass = 400,                                                       //phpass                                                    
        TACACS_ = 16100,                                                    //TACACS+                                                   
        SIP_digest_authentication_MD5 = 11400,                              //SIP digest authentication (MD5)                           
        IKE_PSK_MD5 = 5300,                                                 //IKE-PSK MD5                                               
        IKE_PSK_SHA1 = 5400,                                                //IKE-PSK SHA1                                              
        SNMPv3_HMAC_MD5_96 = 25100,                                         //SNMPv3 HMAC-MD5-96                                        
        SNMPv3_HMAC_MD5_96_HMAC_SHA1_96 = 25000,                            //SNMPv3 HMAC-MD5-96/HMAC-SHA1-96                           
        SNMPv3_HMAC_SHA1_96 = 25200,                                        //SNMPv3 HMAC-SHA1-96                                       
        SNMPv3_HMAC_SHA224_128 = 26700,                                     //SNMPv3 HMAC-SHA224-128                                    
        SNMPv3_HMAC_SHA256_192 = 26800,                                     //SNMPv3 HMAC-SHA256-192                                    
        SNMPv3_HMAC_SHA384_256 = 26900,                                     //SNMPv3 HMAC-SHA384-256                                    
        SNMPv3_HMAC_SHA512_384 = 27300,                                     //SNMPv3 HMAC-SHA512-384                                    
        WPA_EAPOL_PBKDF2 = 2500,                                            //WPA-EAPOL-PBKDF2                                          
        WPA_EAPOL_PMK = 2501,                                               //WPA-EAPOL-PMK                                             
        WPA_PBKDF2_PMKID_EAPOL = 22000,                                     //WPA-PBKDF2-PMKID+EAPOL                                    
        WPA_PMK_PMKID_EAPOL = 22001,                                        //WPA-PMK-PMKID+EAPOL                                       
        WPA_PMKID_PBKDF2 = 16800,                                           //WPA-PMKID-PBKDF2                                          
        WPA_PMKID_PMK = 16801,                                              //WPA-PMKID-PMK                                             
        IPMI2_RAKP_HMAC_SHA1 = 7300,                                        //IPMI2 RAKP HMAC-SHA1                                      
        CRAM_MD5 = 10200,                                                   //CRAM-MD5                                                  
        JWT_JSON_Web_Token = 16500,                                         //JWT (JSON Web Token)                                      
        Radmin3 = 29200,                                                    //Radmin3                                                   
        Kerberos_5_etype_17_TGS_REP = 19600,                                //Kerberos 5, etype 17, TGS-REP                             
        Kerberos_5_etype_17_Pre_Auth = 19800,                               //Kerberos 5, etype 17, Pre-Auth                            
        Kerberos_5_etype_17_DB = 28800,                                     //Kerberos 5, etype 17, DB                                  
        Kerberos_5_etype_18_TGS_REP = 19700,                                //Kerberos 5, etype 18, TGS-REP                             
        Kerberos_5_etype_18_Pre_Auth = 19900,                               //Kerberos 5, etype 18, Pre-Auth                            
        Kerberos_5_etype_18_DB = 28900,                                     //Kerberos 5, etype 18, DB                                  
        Kerberos_5_etype_23_AS_REQ_Pre_Auth = 7500,                         //Kerberos 5, etype 23, AS-REQ Pre-Auth                     
        Kerberos_5_etype_23_TGS_REP = 13100,                                //Kerberos 5, etype 23, TGS-REP                             
        Kerberos_5_etype_23_AS_REP = 18200,                                 //Kerberos 5, etype 23, AS-REP                              
        NetNTLMv1_NetNTLMv1_ESS = 5500,                                     //NetNTLMv1 / NetNTLMv1+ESS                                 
        NetNTLMv1_NetNTLMv1_ESS_NT = 27000,                                 //NetNTLMv1 / NetNTLMv1+ESS (NT)                            
        NetNTLMv2 = 5600,                                                   //NetNTLMv2                                                 
        NetNTLMv2_NT = 27100,                                               //NetNTLMv2 (NT)                                            
        Flask_Session_Cookie_salt_salt_pass = 29100,                        //Flask Session Cookie ($salt.$salt.$pass)                  
        iSCSI_CHAP_authentication_MD5_CHAP = 4800,                          //iSCSI CHAP authentication, MD5(CHAP)                      
        RACF = 8500,                                                        //RACF                                                      
        AIX_smd5 = 6300,                                                    //AIX {smd5}                                    
        AIX_ssha1 = 6700,                                                   //AIX {ssha1}                                   
        AIX_ssha256 = 6400,                                                 //AIX {ssha256}                                 
        AIX_ssha512 = 6500,                                                 //AIX {ssha512}                                 
        LM = 3000,                                                          //LM 
        QNX_etc_shadow_MD5 = 19000,                                         //QNX / etc / shadow(MD5) 
        QNX_etc_shadow_SHA256 = 19100,                                      //QNX / etc / shadow(SHA256) 
        QNX_etc_shadow_SHA512 = 19200,                                      //QNX / etc / shadow(SHA512) 
        DPAPI_masterkey_file_v1_context_1_and_2 = 15300,                    //DPAPI masterkey file v1 (context 1 and 2)     
        DPAPI_masterkey_file_v1_context_3 = 15310,                          //DPAPI masterkey file v1 (context 3)           
        DPAPI_masterkey_file_v2_context_1_and_2 = 15900,                    //DPAPI masterkey file v2 (context 1 and 2)     
        DPAPI_masterkey_file_v2_context_3 = 15910,                          //DPAPI masterkey file v2 (context 3)           
        GRUB_2 = 7200,                                                      //GRUB 2 
        MS_AzureSync_PBKDF2_HMAC_SHA256 = 12800,                            //MS - AzureSync PBKDF2 - HMAC - SHA256 
        BSDi_Crypt_Extended_DES = 12400,                                    //BSDi Crypt, Extended DES                      
        NTLM = 1000,                                                        //NTLM                                          
        Radmin2 = 9900,                                                     //Radmin2                                       
        Samsung_Android_Value_PIN = 5800,                                //Samsung Android Value/PIN                  
        Windows_Hello_PIN_Value = 28100,                                 //Windows Hello PIN/Value                    
        Windows_Phone_8_PIN_Value = 13800,                               //Windows Phone 8+ PIN/Value                 
        Cisco_ASA_MD5 = 2410,                                               //Cisco-ASA MD5                                 
        Cisco_IOS_8_PBKDF2_SHA256 = 9200,                                   //Cisco-IOS $8$ (PBKDF2-SHA256)                 
        Cisco_IOS_9_scrypt = 9300,                                          //Cisco - IOS $9$ (scrypt) 
        Cisco_IOS_type_4_SHA256 = 5700,                                     //Cisco - IOS type 4(SHA256) 
        Cisco_PIX_MD5 = 2400,                                               //Cisco - PIX MD5 
        Citrix_NetScaler_SHA1 = 8100,                                       //Citrix NetScaler(SHA1) 
        Citrix_NetScaler_SHA512 = 22200,                                    //Citrix NetScaler(SHA512) 
        Domain_Cached_Credentials_DCC_MS_Cache = 1100,                      //Domain Cached Credentials(DCC), MS Cache      
        Domain_Cached_Credentials_2_DCC2_MS_Cache_2 = 2100,                 //Domain Cached Credentials 2 (DCC2), MS Cache 2
        FortiGate_FortiOS = 7000,                                           //FortiGate (FortiOS)                           
        FortiGate256_FortiOS256 = 26300,                                    //FortiGate256(FortiOS256) 
        ArubaOS = 125,                                                      //ArubaOS 
        Juniper_IVE = 501,                                                  //Juniper IVE
        Juniper_NetScreen_SSG_ScreenOS = 22,                                //Juniper NetScreen/SSG (ScreenOS)
        Juniper_NetBSD_sha1crypt = 15100,                                   //Juniper/NetBSD sha1crypt
        iPhone_passcode_UID_key_System_Keybag = 26500,                      //iPhone passcode (UID key + System Keybag)
        macOS_v10_4_macOS_10_5_macOS_v10_6 = 122,                           //macOS v10.4, macOS v10.5, macOS v10.6
        macOS_v10_7 = 1722,                                                 //macOS v10.7
        macOS_v10_8_PBKDF2_SHA512 = 7100,                                   //macOS v10.8+ (PBKDF2-SHA512)
        bcrypt_2_Blowfish_Unix = 3200,                                      //bcrypt $2*$, Blowfish (Unix)
        md5crypt_MD5_Unix_Cisco_IOS_1_MD5 = 500,                            //md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
        descrypt_DES_Unix_Traditional_DES = 1500,                           //descrypt, DES (Unix), Traditional DES
        sha1_salt_sha1_utf16le_username_utf16le_pass = 29000,               //sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))
        sha256crypt_5_SHA256_Unix = 7400,                                   //sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))
        sha512crypt_6_SHA512_Unix = 1800,                                   //sha512crypt $6$, SHA512 (Unix)
        SQLCipher = 24600,                                                  //SQLCipher
        MSSQL_2000 = 131,                                                   //SQLCipher
        MSSQL_2005 = 132,                                                   //MSSQL (2005)
        MSSQL_2012_2014 = 1731,                                             //MSSQL (2005)
        MongoDB_ServerKey_SCRAM_SHA_1 = 24100,                              //MSSQL (2005)
        MongoDB_ServerKey_SCRAM_SHA_256 = 24200,                            //MongoDB ServerKey SCRAM-SHA-256
        PostgreSQL = 12,                                                    //PostgreSQL
        PostgreSQL_CRAM_MD5 = 11100,                                        //PostgreSQL CRAM (MD5)
        PostgreSQL_SCRAM_SHA_256 = 28600,                                   //PostgreSQL SCRAM-SHA-256
        Oracle_H_Type_Oracle_7 = 3100,                                      //Oracle H: Type (Oracle 7+)
        Oracle_S_Type_Oracle_11 = 112,                                      //Oracle S: Type (Oracle 11+)
        Oracle_T_Type_Oracle_12 = 12300,                                    //Oracle T: Type (Oracle 12+)
        MySQL_A_sha256crypt = 7401,                                         //MySQL $A$ (sha256crypt)
        MySQL_CRAM_SHA1 = 11200,                                            //MySQL CRAM (SHA1)
        MySQL323 = 200,                                                     //MySQL323
        MySQL4_1_MySQL5 = 300,                                              //MySQL4.1/MySQL5
        Sybase_ASE = 8000,                                                  //Sybase ASE
        DNSSEC_NSEC3 = 8300,                                                //Sybase ASE
        KNX_IP_Secure_Device_Authentication_Code = 25900,                   //KNX IP Secure - Device Authentication Code   
        CRAM_MD5_Dovecot = 16400,                                           //CRAM-MD5 Dovecot                             
        SSHA_256_Base64_LDAP_SSHA256 = 1411,                                //SSHA-256(Base64), LDAP{ SSHA256}             
        SSHA_512_Base64_LDAP_SSHA512 = 1711,                                //SSHA-512(Base64), LDAP{ SSHA512}             
        Dahua_Authentication_MD5 = 24900,                                   //Dahua Authentication MD5                     
        RedHat_389_DS_LDAP_PBKDF2_HMAC_SHA256 = 10901,                      //RedHat 389-DS LDAP (PBKDF2-HMAC-SHA256)      
        FileZilla_Server_0_9_55 = 15000,                                    //FileZilla Server >= 0.9.55                   
        ColdFusion_10 = 12600,                                              //ColdFusion 10+                               
        Apache_apr1_MD5_md5apr1_MD5_APR = 1600,                             //Apache $apr1$ MD5, md5apr1, MD5 (APR)        
        Episerver_6_x_NET_4 = 141,                                          //Episerver 6.x < .NET 4                       
        Episerver_6_x_NET_4_2 = 1441,                                       //Episerver 6.x >= .NET 4                      
        hMailServer = 1421,                                                 //hMailServer                                  
        nsldap_SHA_1_Base64_Netscape_LDAP_SHA = 101,                        //nsldap, SHA-1(Base64), Netscape LDAP SHA     
        nsldaps_SSHA_1_Base64_Netscape_LDAP_SSHA = 111,                     //nsldaps, SSHA-1(Base64), Netscape LDAP SSHA  
        SAP_CODVN_B_BCODE = 7700,                                           //SAP CODVN B (BCODE)                          
        SAP_CODVN_B_BCODE_from_RFC_READ_TABLE = 7701,                       //SAP CODVN B(BCODE) from RFC_READ_TABLE       
        SAP_CODVN_F_G_PASSCODE = 7800,                                      //SAP CODVN F/G (PASSCODE)                     
        SAP_CODVN_F_G_PASSCODE_from_RFC_READ_TABLE = 7801,                  //SAP CODVN F/G (PASSCODE) from RFC_READ_TABLE 
        SAP_CODVN_H_PWDSALTEDHASH_iSSHA_1 = 10300,                          //SAP CODVN H(PWDSALTEDHASH) iSSHA - 1         
        PeopleSoft = 133,                                                   //PeopleSoft                                   
        PeopleSoft_PS_TOKEN = 13500,                                        //PeopleSoft PS_TOKEN                          
        SolarWinds_Orion = 21500,                                           //SolarWinds Orion                             
        SolarWinds_Orion_v2 = 21501,                                        //SolarWinds Orion v2                          
        SolarWinds_Serv_U = 24,                                             //SolarWinds Serv - U                          
        Lotus_Notes_Domino_5 = 8600,                                        //Lotus Notes / Domino 5                       
        Lotus_Notes_Domino_6 = 8700,                                        //Lotus Notes / Domino 6                       
        Lotus_Notes_Domino_8 = 9100,                                        //Lotus Notes / Domino 8                       
        OpenEdge_Progress_Encode = 26200,                                   //OpenEdge Progress Encode                     
        Oracle_Transportation_Management_SHA256 = 20600,                    //Oracle Transportation Management(SHA256)     
        Huawei_sha1_md5_pass_salt = 4711,                                   //Huawei sha1(md5($pass).$salt)                
        AuthMe_sha256 = 20711,                                              //AuthMe sha256                                
        AES_Crypt_SHA256 = 22400,                                           //AES Crypt(SHA256)
        VMware_VMX_PBKDF2_HMAC_SHA1_AES_256_CBC = 27400,                    //VMware VMX(PBKDF2 - HMAC - SHA1 + AES - 256 - CBC)
        LUKS_v1_legacy = 14600,                                             //LUKS v1(legacy) | Full - Disk Encryption(FDE)
        LUKS_v1_RIPEMD_160_AES = 29541,                                     //LUKS v1 RIPEMD-160 + AES                          
        LUKS_v1_RIPEMD_160_Serpent = 29542,                                 //LUKS v1 RIPEMD-160 + Serpent                      
        LUKS_v1_RIPEMD_160_Twofish = 29543,                                 //LUKS v1 RIPEMD-160 + Twofish                      
        LUKS_v1_SHA_1_AES = 29511,                                          //LUKS v1 SHA-1 + AES                               
        LUKS_v1_SHA_1_Serpent = 29512,                                      //LUKS v1 SHA-1 + Serpent                           
        LUKS_v1_SHA_1_Twofish = 29513,                                      //LUKS v1 SHA-1 + Twofish                           
        LUKS_v1_SHA_256_AES = 29521,                                        //LUKS v1 SHA-256 + AES                             
        LUKS_v1_SHA_256_Serpent = 29522,                                    //LUKS v1 SHA-256 + Serpent                         
        LUKS_v1_SHA_256_Twofish = 29523,                                    //LUKS v1 SHA-256 + Twofish                         
        LUKS_v1_SHA_512_AES = 29531,                                        //LUKS v1 SHA-512 + AES                             
        LUKS_v1_SHA_512_Serpent = 29532,                                    //LUKS v1 SHA-512 + Serpent                         
        LUKS_v1_SHA_512_Twofish = 29533,                                    //LUKS v1 SHA-512 + Twofish                         
        VeraCrypt_RIPEMD160_XTS_512_bit_legacy = 13711,                     //VeraCrypt RIPEMD160 + XTS 512 bit(legacy) 
        VeraCrypt_RIPEMD160_XTS_1024_bit_legacy = 13712,                    //VeraCrypt RIPEMD160 + XTS 1024 bit(legacy)
        VeraCrypt_RIPEMD160_XTS_1536_bit_legacy = 13713,                    //VeraCrypt RIPEMD160 + XTS 1536 bit(legacy)
        VeraCrypt_RIPEMD160_XTS_512_bit_boot_mode_legacy = 13741,           //VeraCrypt RIPEMD160 + XTS 512 bit + boot - mode(legacy) 
        VeraCrypt_RIPEMD160_XTS_1024_bit_boot_mode_legacy = 13742,          //VeraCrypt RIPEMD160 + XTS 1024 bit + boot - mode(legacy)
        VeraCrypt_RIPEMD160_XTS_1536_bit_boot_mode_legacy = 13743,          //VeraCrypt RIPEMD160 + XTS 1536 bit + boot - mode(legacy)
        VeraCrypt_RIPEMD160_XTS_512_bit = 29411,                            //VeraCrypt RIPEMD160 + XTS 512 bit 
        VeraCrypt_RIPEMD160_XTS_1024_bit = 29412,                           //VeraCrypt RIPEMD160 + XTS 1024 bit
        VeraCrypt_RIPEMD160_XTS_1536_bit = 29413,                           //VeraCrypt RIPEMD160 + XTS 1536 bit
        VeraCrypt_RIPEMD160_XTS_512_bit_boot_mode = 29441,                  //VeraCrypt RIPEMD160 + XTS 512 bit + boot - mode 
        VeraCrypt_RIPEMD160_XTS_1024_bit_boot_mode = 29442,                 //VeraCrypt RIPEMD160 + XTS 1024 bit + boot - mode
        VeraCrypt_RIPEMD160_XTS_1536_bit_boot_mode = 29443,                 //VeraCrypt RIPEMD160 + XTS 1536 bit + boot - mode
        VeraCrypt_SHA256_XTS_512_bit_legacy = 13751,                        //VeraCrypt SHA256 + XTS 512 bit(legacy) 
        VeraCrypt_SHA256_XTS_1024_bit_legacy = 13752,                       //VeraCrypt SHA256 + XTS 1024 bit(legacy)
        VeraCrypt_SHA256_XTS_1536_bit_legacy = 13753,                       //VeraCrypt SHA256 + XTS 1536 bit(legacy)
        VeraCrypt_SHA256_XTS_512_bit_boot_mode_legacy = 13761,              //VeraCrypt SHA256 + XTS 512 bit + boot - mode(legacy) 
        VeraCrypt_SHA256_XTS_1024_bit_boot_mode_legacy = 13762,             //VeraCrypt SHA256 + XTS 1024 bit + boot - mode(legacy)
        VeraCrypt_SHA256_XTS_1536_bit_boot_mode_legacy = 13763,             //VeraCrypt SHA256 + XTS 1536 bit + boot - mode(legacy)
        VeraCrypt_SHA256_XTS_512_bit = 29451,                               //VeraCrypt SHA256 + XTS 512 bit 
        VeraCrypt_SHA256_XTS_1024_bit = 29452,                              //VeraCrypt SHA256 + XTS 1024 bit
        VeraCrypt_SHA256_XTS_1536_bit = 29453,                              //VeraCrypt SHA256 + XTS 1536 bit
        VeraCrypt_SHA256_XTS_512_bit_boot_mode = 29461,                     //VeraCrypt SHA256 + XTS 512 bit + boot - mode 
        VeraCrypt_SHA256_XTS_1024_bit_boot_mode = 29462,                    //VeraCrypt SHA256 + XTS 1024 bit + boot - mode
        VeraCrypt_SHA256_XTS_1536_bit_boot_mode = 29463,                    //VeraCrypt SHA256 + XTS 1536 bit + boot - mode
        VeraCrypt_SHA512_XTS_512_bit_legacy = 13721,                        //VeraCrypt SHA512 + XTS 512 bit(legacy) 
        VeraCrypt_SHA512_XTS_1024_bit_legacy = 13722,                       //VeraCrypt SHA512 + XTS 1024 bit(legacy)
        VeraCrypt_SHA512_XTS_1536_bit_legacy = 13723,                       //VeraCrypt SHA512 + XTS 1536 bit(legacy)
        VeraCrypt_SHA512_XTS_512_bit = 29421,                               //VeraCrypt SHA512 + XTS 512 bit 
        VeraCrypt_SHA512_XTS_1024_bit = 29422,                              //VeraCrypt SHA512 + XTS 1024 bit
        VeraCrypt_SHA512_XTS_1536_bit = 29423,                              //VeraCrypt SHA512 + XTS 1536 bit
        VeraCrypt_Streebog_512_XTS_512_bit_legacy = 13771,                  //VeraCrypt Streebog - 512 + XTS 512 bit(legacy) 
        VeraCrypt_Streebog_512_XTS_1024_bit_legacy = 13772,                 //VeraCrypt Streebog - 512 + XTS 1024 bit(legacy)
        VeraCrypt_Streebog_512_XTS_1536_bit_legacy = 13773,                 //VeraCrypt Streebog - 512 + XTS 1536 bit(legacy)
        VeraCrypt_Streebog_512_XTS_512_bit_boot_mode_legacy = 13781,        //VeraCrypt Streebog - 512 + XTS 512 bit + boot - mode(legacy) 
        VeraCrypt_Streebog_512_XTS_1024_bit_boot_mode_legacy = 13782,       //VeraCrypt Streebog - 512 + XTS 1024 bit + boot - mode(legacy)
        VeraCrypt_Streebog_512_XTS_1536_bit_boot_mode_legacy = 13783,       //VeraCrypt Streebog - 512 + XTS 1536 bit + boot - mode(legacy)
        VeraCrypt_Streebog_512_XTS_512_bit = 29471,                         //VeraCrypt Streebog - 512 + XTS 512 bit 
        VeraCrypt_Streebog_512_XTS_1024_bit = 29472,                        //VeraCrypt Streebog - 512 + XTS 1024 bit
        VeraCrypt_Streebog_512_XTS_1536_bit = 29473,                        //VeraCrypt Streebog - 512 + XTS 1536 bit
        VeraCrypt_Streebog_512_XTS_512_bit_boot_mode = 29481,               //VeraCrypt Streebog - 512 + XTS 512 bit + boot - mode 
        VeraCrypt_Streebog_512_XTS_1024_bit_boot_mode = 29482,              //VeraCrypt Streebog - 512 + XTS 1024 bit + boot - mode
        VeraCrypt_Streebog_512_XTS_1536_bit_boot_mode = 29483,              //VeraCrypt Streebog - 512 + XTS 1536 bit + boot - mode
        VeraCrypt_Whirlpool_XTS_512_bit_legacy = 13731,                     //VeraCrypt Whirlpool + XTS 512 bit(legacy) 
        VeraCrypt_Whirlpool_XTS_1024_bit_legacy = 13732,                    //VeraCrypt Whirlpool + XTS 1024 bit(legacy)
        VeraCrypt_Whirlpool_XTS_1536_bit_legacy = 13733,                    //VeraCrypt Whirlpool + XTS 1536 bit(legacy)
        VeraCrypt_Whirlpool_XTS_512_bit = 29431,                            //VeraCrypt Whirlpool + XTS 512 bit 
        VeraCrypt_Whirlpool_XTS_1024_bit = 29432,                           //VeraCrypt Whirlpool + XTS 1024 bit
        VeraCrypt_Whirlpool_XTS_1536_bit = 29433,                           //VeraCrypt Whirlpool + XTS 1536 bit
        BestCrypt_v3_Volume_Encryption = 23900,                             //BestCrypt v3 Volume Encryption                          
        FileVault_2 = 16700,                                                //FileVault 2                                             
        VirtualBox_PBKDF2_HMAC_SHA256_AES_128_XTS = 27500,                  //VirtualBox(PBKDF2 - HMAC - SHA256 & AES - 128 - XTS)    
        VirtualBox_PBKDF2_HMAC_SHA256_AES_256_XTS = 27600,                  //VirtualBox(PBKDF2 - HMAC - SHA256 & AES - 256 - XTS)    
        DiskCryptor_SHA512_XTS_512_bit = 20011,                             //DiskCryptor SHA512 + XTS 512 bit                        
        DiskCryptor_SHA512_XTS_1024_bit = 20012,                            //DiskCryptor SHA512 + XTS 1024 bit                       
        DiskCryptor_SHA512_XTS_1536_bit = 20013,                            //DiskCryptor SHA512 + XTS 1536 bit                       
        BitLocker = 22100,                                                  //BitLocker                                               
        Android_FDE_Samsung_DEK = 12900,                                    //Android FDE(Samsung DEK)                                
        Android_FDE_4_3 = 8800,                                             //Android FDE <= 4.3                                      
        Apple_File_System_APFS = 18300,                                     //Apple File System(APFS)                                 
        TrueCrypt_RIPEMD160_XTS_512_bit_legacy = 6211,                      //TrueCrypt RIPEMD160 + XTS 512 bit(legacy)               
        TrueCrypt_RIPEMD160_XTS_1024_bit_legacy = 6212,                     //TrueCrypt RIPEMD160 + XTS 1024 bit(legacy)              
        TrueCrypt_RIPEMD160_XTS_1536_bit_legacy = 6213,                     //TrueCrypt RIPEMD160 + XTS 1536 bit(legacy)              
        TrueCrypt_RIPEMD160_XTS_512_bit_boot_mode_legacy = 6241,            //TrueCrypt RIPEMD160 + XTS 512 bit + boot - mode(legacy) 
        TrueCrypt_RIPEMD160_XTS_1024_bit_boot_mode_legacy = 6242,           //TrueCrypt RIPEMD160 + XTS 1024 bit + boot - mode(legacy)
        TrueCrypt_RIPEMD160_XTS_1536_bit_boot_mode_legacy = 6243,           //TrueCrypt RIPEMD160 + XTS 1536 bit + boot - mode(legacy)
        TrueCrypt_RIPEMD160_XTS_512_bit = 29311,                            //TrueCrypt RIPEMD160 + XTS 512 bit                       
        TrueCrypt_RIPEMD160_XTS_1024_bit = 29312,                           //TrueCrypt RIPEMD160 + XTS 1024 bit                      
        TrueCrypt_RIPEMD160_XTS_1536_bit = 29313,                           //TrueCrypt RIPEMD160 + XTS 1536 bit                      
        TrueCrypt_RIPEMD160_XTS_512_bit_boot_mode = 29341,                  //TrueCrypt RIPEMD160 + XTS 512 bit + boot - mode         
        TrueCrypt_RIPEMD160_XTS_1024_bit_boot_mode = 29342,                 //TrueCrypt RIPEMD160 + XTS 1024 bit + boot - mode        
        TrueCrypt_RIPEMD160_XTS_1536_bit_boot_mode = 29343,                 //TrueCrypt RIPEMD160 + XTS 1536 bit + boot - mode        
        TrueCrypt_SHA512_XTS_512_bit_legacy = 6221,                         //TrueCrypt SHA512 + XTS 512 bit(legacy)                  
        TrueCrypt_SHA512_XTS_1024_bit_legacy = 6222,                        //TrueCrypt SHA512 + XTS 1024 bit(legacy)                 
        TrueCrypt_SHA512_XTS_1536_bit_legacy = 6223,                        //TrueCrypt SHA512 + XTS 1536 bit(legacy)                 
        TrueCrypt_SHA512_XTS_512_bit = 29321,                               //TrueCrypt SHA512 + XTS 512 bit                          
        TrueCrypt_SHA512_XTS_1024_bit = 29322,                              //TrueCrypt SHA512 + XTS 1024 bit                         
        TrueCrypt_SHA512_XTS_1536_bit = 29323,                              //TrueCrypt SHA512 + XTS 1536 bit                         
        TrueCrypt_Whirlpool_XTS_512_bit_legacy = 6231,                      //TrueCrypt Whirlpool + XTS 512 bit(legacy)               
        TrueCrypt_Whirlpool_XTS_1024_bit_legacy = 6232,                     //TrueCrypt Whirlpool + XTS 1024 bit(legacy)              
        TrueCrypt_Whirlpool_XTS_1536_bit_legacy = 6233,                     //TrueCrypt Whirlpool + XTS 1536 bit(legacy)              
        TrueCrypt_Whirlpool_XTS_512_bit = 29331,                            //TrueCrypt Whirlpool + XTS 512 bit                       
        TrueCrypt_Whirlpool_XTS_1024_bit = 29332,                           //TrueCrypt Whirlpool + XTS 1024 bit                      
        TrueCrypt_Whirlpool_XTS_1536_bit = 29333,                           //TrueCrypt Whirlpool + XTS 1536 bit                      
        eCryptfs = 12200,                                                   //eCryptfs                                                       
        PDF_1_1_1_3_Acrobat_2_4 = 10400,                                    //PDF 1.1 - 1.3(Acrobat 2 - 4)                                   
        PDF_1_1_1_3_Acrobat_2_4_collider_1 = 10410,                         //PDF 1.1 - 1.3(Acrobat 2 - 4), collider #1                      
        PDF_1_1_1_3_Acrobat_2_4_collider_2 = 10420,                         //PDF 1.1 - 1.3(Acrobat 2 - 4), collider #2                      
        PDF_1_4_1_6_Acrobat_5_8 = 10500,                                    //PDF 1.4 - 1.6(Acrobat 5 - 8)                                   
        PDF_1_4_1_6_Acrobat_5_8_user_and_owner_pass = 25400,                //PDF 1.4 - 1.6(Acrobat 5 - 8) - user and owner pass             
        PDF_1_7_Level_3_Acrobat_9 = 10600,                                  //PDF 1.7 Level 3 (Acrobat 9)                                    
        PDF_1_7_Level_8_Acrobat_10_11 = 10700,                              //PDF 1.7 Level 8(Acrobat 10 - 11)                               
        MS_Office_2007 = 9400,                                              //MS Office 2007                                                 
        MS_Office_2010 = 9500,                                              //MS Office 2010                                                 
        MS_Office_2013 = 9600,                                              //MS Office 2013                                                 
        MS_Office_2016_SheetProtection = 25300,                             //MS Office 2016 - SheetProtection                               
        MS_Office_2003_0_1_MD5_RC4 = 9700,                                  //MS Office <= 2003 $0 /$1, MD5 + RC4                            
        MS_Office_2003_0_1_MD5_RC4_collider_1 = 9710,                       //MS Office <= 2003 $0 /$1, MD5 + RC4, collider #1               
        MS_Office_2003_0_1_MD5_RC4_collider_2 = 9720,                       //MS Office <= 2003 $0 /$1, MD5 + RC4, collider #2               
        MS_Office_2003_3_SHA1_RC4_collider_1 = 9810,                        //MS Office <= 2003 $3, SHA1 + RC4, collider #1                  
        MS_Office_2003_3_SHA1_RC4_collider_2 = 9820,                        //MS Office <= 2003 $3, SHA1 + RC4, collider #2                  
        MS_Office_2003_3_4_SHA1_RC4 = 9800,                                 //MS Office <= 2003 $3 /$4, SHA1 + RC4                           
        Open_Document_Format_ODF_1_2_SHA_256_AES = 18400,                   //Open Document Format(ODF) 1.2(SHA - 256, AES)                  
        Open_Document_Format_ODF_1_1_SHA_1_Blowfish = 18600,                //Open Document Format(ODF) 1.1(SHA - 1, Blowfish)               
        Apple_Secure_Notes = 16200,                                         //Apple Secure Notes                                             
        Apple_iWork = 23300,                                                //Apple iWork                                                    
        Value1_agilekeychain = 6600,                                     //1Value, agilekeychain                                       
        Value1_cloudkeychain = 8200,                                     //1Value, cloudkeychain                                       
        Value_Safe_v2 = 9000,                                            //Value Safe v2                                               
        Value_Safe_v3 = 5200,                                            //Value Safe v3                                               
        LastPass_LastPass_sniffed = 6800,                                   //LastPass + LastPass sniffed                                    
        KeePass_1_AES_Twofish_and_KeePass_2_AES = 13400,                    //KeePass 1 (AES/Twofish) and KeePass 2 (AES)                    
        KeePass_1_AES_Twofish_and_KeePass_2_AES_keyfile_only_mode = 29700,  //KeePass 1(AES / Twofish) and KeePass 2 (AES) -keyfile only mode
        Bitwarden = 23400,                                                  //Bitwarden                                                      
        Ansible_Vault = 16900,                                              //Ansible Vault                                                  
        Mozilla_key3_db = 26000,                                            //Mozilla key3.db                                                
        Mozilla_key4_db = 26100,                                            //Mozilla key4.db                                                
        Apple_Keychain = 23100,                                             //Apple Keychain                                                 
        Zip7 = 11600,                                                       //7-Zip                                                          
        RAR3_hp = 12500,                                                    //RAR3-hp                                                        
        RAR3_p_Compressed = 23800,                                          //RAR3-p (Compressed)                                            
        RAR3_p_Uncompressed = 23700,                                        //RAR3-p (Uncompressed)                              
        RAR5 = 13000,                                                       //RAR5                                               
        PKZIP_Compressed_Multi_File = 17220,                                //PKZIP(Compressed Multi - File)                     
        PKZIP_Compressed = 17200,                                           //PKZIP(Compressed)                                  
        PKZIP_Mixed_Multi_File = 17225,                                     //PKZIP(Mixed Multi - File)                          
        PKZIP_Mixed_Multi_File_Checksum_Only = 17230,                       //PKZIP(Mixed Multi - File Checksum - Only)          
        PKZIP_Uncompressed = 17210,                                         //PKZIP(Uncompressed)                                
        PKZIP_Master_Key = 20500,                                           //PKZIP Master Key                                   
        PKZIP_Master_Key_6_byte_optimization = 20510,                       //PKZIP Master Key (6 byte optimization)             
        SecureZIP_AES_128 = 23001,                                          //SecureZIP AES - 128                                
        SecureZIP_AES_192 = 23002,                                          //SecureZIP AES - 192                                
        SecureZIP_AES_256 = 23003,                                          //SecureZIP AES - 256                                
        WinZip = 13600,                                                     //WinZip                                             
        Android_Backup = 18900,                                             //Android Backup                                     
        Stuffit5 = 24700,                                                  //Stuffit5                                           
        AxCrypt_1 = 13200,                                                 //AxCrypt 1                                          
        AxCrypt_1_in_memory_SHA1 = 13300,                                  //AxCrypt 1 in-memory SHA1                           
        AxCrypt_2_AES_128 = 23500,                                         //AxCrypt 2 AES - 128                                
        AxCrypt_2_AES_256 = 23600,                                         //AxCrypt 2 AES - 256                                
        iTunes_backup_10_0 = 14700,                                         //iTunes backup < 10.0                               
        iTunes_backup_10_0_2 = 14800,                                       //iTunes backup >= 10.0                              
        WBB3_Woltlab_Burning_Board = 8400,                                  //WBB3(Woltlab Burning Board)                        
        PHPS = 2612,                                                        //PHPS                                               
        SMF_Simple_Machines_Forum_v1_1 = 121,                               //SMF(Simple Machines Forum) > v1.1                  
        MediaWiki_B_type = 3711,                                            //MediaWiki B type                                   
        Redmine = 4521,                                                     //Redmine                                            
        Umbraco_HMAC_SHA1 = 24800,                                          //Umbraco HMAC-SHA1                                  
        Joomla_2_5_18 = 11,                                                 //Joomla < 2.5.18                                    
        OpenCart = 13900,                                                   //OpenCart                                           
        PrestaShop = 11000,                                                 //PrestaShop                                         
        Tripcode = 16000,                                                  //Tripcode                                           
        Drupal7 = 7900,                                                    //Drupal7                                            
        PunBB = 4522,                                                       //PunBB                                              
        MyBB_1_2_IPB2_Invision_Power_Board = 2811,                          //MyBB 1.2+, IPB2+ (Invision Power Board)            
        vBulletin_v3_8_5 = 2611,                                            //vBulletin < v3.8.5                                 
        vBulletin_v3_8_5_2 = 2711,                                          //vBulletin >= v3.8.5                                
        bcrypt_md5_pass_bcryptmd5 = 25600,                                  //bcrypt(md5($pass)) / bcryptmd5                     
        bcrypt_sha1_pass_bcryptsha1 = 25800,                                //bcrypt(sha1($pass)) / bcryptsha1                   
        bcrypt_sha512_pass_bcryptsha512 = 28400,                            //bcrypt(sha512($pass)) / bcryptsha512               
        osCommerce_xt_Commerce = 21,                                        //osCommerce, xt: Commerce                           
        TOTP_HMAC_SHA1 = 18100,                                             //TOTP(HMAC - SHA1)                                  
        STDOUT = 2000,                                                     //STDOUT                                             
        Plaintext = 99999,                                                 //Plaintext                                          
        Web2py_pbkdf2_sha512 = 21600,                                       //Web2py pbkdf2 - sha512                             
        Django_PBKDF2_SHA256 = 10000,                                       //Django(PBKDF2 - SHA256)                            
        Django_SHA_1 = 124,                                                 //Django(SHA - 1)                                    
        Atlassian_PBKDF2_HMAC_SHA1 = 12001,                                 //Atlassian(PBKDF2 - HMAC - SHA1)                    
        Ruby_on_Rails_Restful_Authentication = 19500,                       //Ruby on Rails Restful-Authentication               
        Ruby_on_Rails_Restful_Auth_one_round_no_sitekey = 27200,            //Ruby on Rails Restful Auth (one round, no sitekey) 
        Python_Werkzeug_MD5_HMAC_MD5_key_salt = 30000,                      //Python Werkzeug MD5(HMAC-MD5 (key = $salt))        
        Python_Werkzeug_SHA256_HMAC_SHA256_key_salt = 30120,                //Python Werkzeug SHA256(HMAC-SHA256 (key = $salt))  
        Python_passlib_pbkdf2_sha512 = 20200,                               //Python passlib pbkdf2-sha512                       
        Python_passlib_pbkdf2_sha256 = 20300,                               //Python passlib pbkdf2-sha256                       
        Python_passlib_pbkdf2_sha1 = 20400,                                 //Python passlib pbkdf2-sha1                         
        PKCS_8_Private_Keys_PBKDF2_HMAC_SHA1_3DES_AES = 24410,              //PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)  
        PKCS_8_Private_Keys_PBKDF2_HMAC_SHA256_3DES_AES = 24420,            //PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)
        JKS_Java_Key_Store_Private_Keys_SHA1 = 15500,                       //JKS Java Key Store Private Keys (SHA1)             
        RSA_DSA_EC_OpenSSH_Private_Keys_0 = 22911,                          //RSA / DSA / EC / OpenSSH Private Keys($0$)         
        RSA_DSA_EC_OpenSSH_Private_Keys_6 = 22921,                          //RSA / DSA / EC / OpenSSH Private Keys($6$)         
        RSA_DSA_EC_OpenSSH_Private_Keys_1_3 = 22931,                        //RSA / DSA / EC / OpenSSH Private Keys($1, $3$)     
        RSA_DSA_EC_OpenSSH_Private_Keys_4 = 22941,                          //RSA/DSA/EC/OpenSSH Private Keys ($4$)              
        RSA_DSA_EC_OpenSSH_Private_Keys_5 = 22951,                          //RSA/DSA/EC/OpenSSH Private Keys ($5$)              
        XMPP_SCRAM_PBKDF2_SHA1 = 23200,                                     //XMPP SCRAM PBKDF2-SHA1                             
        Teamspeak_3_channel_hash = 28300,                                   //Teamspeak 3 (channel hash)                         
        Telegram_Desktop_v2_1_14_PBKDF2_HMAC_SHA1 = 22600,                  //Telegram Desktop < v2.1.14 (PBKDF2-HMAC-SHA1)      
        Telegram_Desktop_v2_1_14_PBKDF2_HMAC_SHA512 = 24500,                //Telegram Desktop >= v2.1.14 (PBKDF2-HMAC-SHA512)   
        Telegram_Mobile_App_Passcode_SHA256 = 22301,                        //Telegram Mobile App Passcode (SHA256)              
        Skype = 23,                                                         //Skype                                              
        Terra_Station_Wallet_AES256_CBC_PBKDF2_pass = 29600,                //Terra Station Wallet (AES256-CBC(PBKDF2($pass)))   
        MetaMask_Wallet = 26600,                                            //MetaMask Wallet                                    
        BitShares_v0_x_sha512_sha512_bin_pass = 21000,                      //BitShares v0.x - sha512(sha512_bin(pass))          
        Bitcoin_WIF_private_key_P2PKH_compressed = 28501,                   //Bitcoin WIF private key (P2PKH), compressed           
        Bitcoin_WIF_private_key_P2PKH_uncompressed = 28502,                 //Bitcoin WIF private key (P2PKH), uncompressed         
        Bitcoin_WIF_private_key_P2WPKH_Bech32_compressed = 28503,           //Bitcoin WIF private key (P2WPKH, Bech32), compressed  
        Bitcoin_WIF_private_key_P2WPKH_Bech32_uncompressed = 28504,         //Bitcoin WIF private key (P2WPKH, Bech32), uncompressed
        Bitcoin_WIF_private_key_P2SH_P2WPKH_compressed = 28505,             //Bitcoin WIF private key (P2SH(P2WPKH)), compressed    
        Bitcoin_WIF_private_key_P2SH_P2WPKH_uncompressed = 28506,           //Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed  
        Bitcoin_Litecoin_wallet_dat = 11300,                                //Bitcoin/Litecoin wallet.dat                           
        Electrum_Wallet_Salt_Type_1_3 = 16600,                              //Electrum Wallet (Salt-Type 1-3)                       
        Electrum_Wallet_Salt_Type_4 = 21700,                                //Electrum Wallet (Salt-Type 4)                         
        Electrum_Wallet_Salt_Type_5 = 21800,                                //Electrum Wallet (Salt-Type 5)                         
        Blockchain_My_Wallet = 12700,                                       //Blockchain, My Wallet                                 
        Blockchain_My_Wallet_V2 = 15200,                                    //Blockchain, My Wallet, V2                             
        Blockchain_My_Wallet_Second_Value_SHA256 = 18800,                //Blockchain, My Wallet, Second Value (SHA256)       
        Stargazer_Stellar_Wallet_XLM = 25500,                               //Stargazer Stellar Wallet XLM                          
        Ethereum_Pre_Sale_Wallet_PBKDF2_HMAC_SHA256 = 16300,                //Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256          
        Ethereum_Wallet_PBKDF2_HMAC_SHA256 = 15600,                         //Ethereum Wallet, PBKDF2-HMAC-SHA256                   
        Ethereum_Wallet_SCRYPT = 15700,                                     //Ethereum Wallet, SCRYPT                               
        MultiBit_Classic_key_MD5 = 22500,                                   //MultiBit Classic .key (MD5)                           
        MultiBit_Classic_wallet_scrypt = 27700,                             //MultiBit Classic .wallet (scrypt)                     
        MultiBit_HD_scrypt = 22700,                                         //MultiBit HD (scrypt)                                  
        Exodus_Desktop_Wallet_scrypt = 28200                                //Exodus Desktop Wallet (scrypt)
    }
}
